# Site settings

title: "Powering Change @ Brigidine College"
email: "webmaster@powertracker.com.au"
googleanalytics: UA-26183233-5

# Build settings

sass:
    style: compressed

# Javascript files

javascript:
    - /js/jquery.min.js
    - /js/bootstrap.min.js

stylesheets:
    - /css/style.css
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

# Define Menu Items for Main and Footer menu

menuitems:
    - url: /
      title: "Home"
    - url: /energy/
      title: "Energy"
    - url: /target/
      title: "Target"
    - url: /about/
      title: "About"
    - url: /contact/
      title: "Contact Us"
